apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lukasboettcher/argo-bug-reproduce.git
    targetRevision: HEAD
    path: test-app/
  destination:
    name: vcluster # deploy test app into vcluster
    namespace: default
  syncPolicy:
    retry:
      limit: 100
      backoff:
        duration: "2s"
        factor: 2
    automated:
      prune: true
      selfHeal: true
