apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
  namespace: test
spec:
  limits:
  - default:
      cpu: "2"
      memory: 4Gi
    defaultRequest:
      cpu: 10m
      memory: 128Mi
    type: Container
